#!/bin/bash

app=$YNH_APP_INSTANCE_NAME
unix_user=$app
dbname=$app
dbuser=$app

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true



domain=$(sudo yunohost app setting $app domain)

sudo service "$app" stop
sudo update-rc.d "$app" remove
sudo rm "/etc/init.d/$app"
sudo yunohost service remove "$app"
sudo rm -rf "/etc/nginx/conf.d/$domain.d/$app.conf"
sudo rm -rf "/var/log/$app.log"
sudo rm -rf "/var/run/yunohost/$app.pid"
sudo rm -rf "/etc/logrotate.d/$app"
sudo rm -rf "/var/www/$app"


sudo service nginx reload || true

# Remove the unix_user account
id "$unix_user" >/dev/null 2>&1 \
  && sudo deluser --quiet --remove-home "$unix_user" >/dev/null \
  || true